[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "sh -c \"/nakama/nakama migrate up --database.address \\\"$DATABASE_URL\\\" && exec /nakama/nakama --database.address \\\"$DATABASE_URL\\\"\""
healthcheckPath = "/v2/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
